<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h1>Carrito de la compra</h1>
    <?php
    echo 'Pedido:' . $cart->getId() . '<br>';
    foreach ($cart->getOrderLines() as $line) {

        echo 'Id Producto: ' . $line->getProduct()->getId() . '<br>';
        echo 'Nombre Producto: ' . $line->getProduct()->getName() . '<br>';
        echo 'Imagen de Producto: <img src="' . $line->getProduct()->getImg() . '" width="100px"><br>';
        echo 'Precio: ' . $line->getPrice() . '€<br>';
        echo 'Cantidad: ' . $line->getAmount() . '<br>';
    }
    ?>
    <a href="index.php?c=order&confirm=1">Confirmar pedido</a>


</body>

</html>