<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <a href="index.php">Volver al inicio</a>
    <h1>Carrito de la compra</h1>
    <?php
    echo 'Pedido:' . $cart->getId() . '<br>';
    foreach ($cart->getOrderLines() as $line) {

        echo 'Id Producto: ' . $line->getProduct()->getId() . '<br>';
        echo 'Nombre Producto: ' . $line->getProduct()->getName() . '<br>';
        echo 'Imagen de Producto: <img src="' . $line->getProduct()->getImg() . '" width="100px"><br>';
        echo 'Precio: ' . $line->getPrice() . '€<br>';
        echo 'Cantidad: ' . $line->getAmount() . '<br>';
        echo '<a href="index.php?c=order&cart=1&id=' . $line->getProduct()->getId() . '">Borrar del carrito</a><br>';
    }

    if (!empty($_SESSION['delProd'])) {
        echo 'Se han eliminado los siguientes productos por falta de stock: <br>';
        foreach ($_SESSION['delProd'] as $product) {
            echo '<img src="' . $product->getImg() . '" width="100px"/>';
            echo $product->getName();
            echo $product->getDescription() . '<br>';
            echo 'Solo quedan en stock ' . $product->getStock() . ' unidades';
        }
    }

    echo 'Precio total del carrito: ' . $cart->getTotalPrice() . '<br>';

    if ($cart->getOrderLines()) {
        echo '<a href="index.php?c=order&confirm=1">Confirmar pedido</a>';
    } else {
        echo 'Añade más productos a tu carrito para confirmar el pedido';
    }
    ?>


</body>

</html>