<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda-Online</title>
</head>

<body>
    <form action="index.php?c=user" method="post">
        <label for="username">Usuario</label>
        <input type="text" name="username" id="username" required>
        <label for="password">Contraseña</label>
        <input type="password" name="password" id="password" required>
        <input type="submit" name="login" value="Iniciar Sesión">
        <a href="index.php?c=user&register=1">¿No tienes cuenta? Regístrate</a>
    </form>
</body>

</html>