<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/style.css">
    <title>Document</title>
</head>
<?php

echo 'Bienvenido:' . $_SESSION['user']->getUsername() . '<br>';
if (!empty($confirmedOrder)) {
    echo 'PEDIDO CONFIRMADO!!!<br>';
}
if (!empty($_SESSION['delProd'])) {
    echo 'No se ha podido confirmar tu pedido por falta de stock de algun producto. Puedes volver a tu carrito!<br>';
}

echo '<a href="index.php?c=user&lo=1">Cerrar Sesión</a><br>';
if ($orders) {
    echo '<a href="index.php?orders=1&c=order">Ver mis pedidos</a><br>';
}
if ($_SESSION['user']->getCart()) {
    echo '<a href="index.php?c=order&cart=1">Carrito de la Compra</a><br>';
}
if ($_SESSION['user']->getRol() >= 2) {
    echo '<a href="index.php?c=product&cp=1">Crear producto</a><br>';
    echo '<a href="index.php?c=user&admin=1">Administrar usuarios</a><br>';
}

foreach ($products as $product) {
    echo '<img src="' . $product->getImg() . '" width="100px"/>';
    echo $product->getName();
    echo $product->getDescription();
    echo '<form method="POST" action="index.php?c=order">
                <select name="amount">';
    for ($i = 1; $i <= ProductRepository::getStock($product->getId()); $i++) {
        echo '<option value="' . $i . '">' . $i . '</option>';
    }
    echo '<input type="hidden" name="id" value="' . $product->getId() . '">';
    echo '<input type="submit" value="Añadir al Carrito"><br>';
    echo '</form>';
}


?>


<body>

</body>

</html>