<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/style.css">
    <title>Document</title>
</head>
<?php

echo 'Bienvenido:' . $_SESSION['user']->getUsername() . '<br>';
echo '<a href="index.php?c=user&lo=1">Cerrar Sesión</a><br>';
if ($_SESSION['user']->getRol() >= 2) {
    echo '<a href="index.php?c=product&cp=1">Crear producto</a><br>';
    echo '<a href="#">Administrar usuarios</a><br>';
}

foreach ($products as $product) {
    echo '<img src="' . $product->getImg() . '" width="100px"/>';
    echo $product->getName();
    echo $product->getDescription();
}


?>


<body>

</body>

</html>