<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda Online</title>
</head>
<form action="index.php?c=product&cp=1" method="post" enctype="multipart/form-data">
    <label for="">Nombre</label>
    <input type="text" name="name" id="">
    <label for="">Descripción</label>
    <input type="text" name="description" id="">
    <input type="file" name="image" id="">
    <label for="">Precio</label>
    <input type="text" name="price" id="">
    <label for="">Cantidad</label>
    <input type="number" name="amount" id="">
    <input type="submit" name="create" value="Crear Producto">
</form>


<body>

</body>

</html>