<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda Online</title>
</head>

<body>
    <form action="index.php?c=user" method="post">
        <label for="username">Nombre de Usuario</label>
        <input type="text" name="username" id="username" required>
        <label for="password">Contraseña</label>
        <input type="password" name="password" id="password" required>
        <label for="password">Dirección</label>
        <input type="text" name="address" id="address" required>
        <input type="submit" name="register" value="Registrarse">
    </form>
    <?php
    if (isset($registerSuccess) && !$registerSuccess) {
        echo 'El usuario no es válido o ya existe';
    }
    ?>
</body>

</html>